name: weather_app
description: "Weather App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1


  #UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  gap: ^3.0.1

  #Navigation
  go_router: ^12.1.1

  #Internet Api & Connection
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  #Bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  path: ^1.8.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  location: ^5.0.3
  get_it: ^7.6.4
  hive_flutter: ^1.1.0
  mask_text_input_formatter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

